import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const stocks = api.stock.getStocks.useQuery();
  return (
    <>
      <Head>
        <title>Flow App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Flow App</h1>
        <pre>{JSON.stringify(stocks.data, null, 1)}</pre>
      </main>
    </>
  );
};

export default Home;
