name: ci

on:
  pull_request:
    branches:
      - develop

jobs:
  prepare:
    name: prepare workspace
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install Dependencies
        run: npm i
      - name: Create workspace artifact
        run: |
          touch workspace.tar.gz
          tar -czf workspace.tar.gz --exclude=workspace.tar.gz .
      - name: Upload workspace artifact
        uses: actions/upload-artifact@v3
        with:
          name: workspace-artifact
          path: workspace.tar.gz

  app-test:
    name: run tests
    runs-on: ubuntu-latest
    needs: prepare

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: test
        run: npm run test
      - name: coverage
        run: npm run coverage

  cleanup:
    name: clean up artifacts
    runs-on: ubuntu-latest
    needs: [app-test]

    steps:
      - name: clean up artifacts
        uses: jimschubert/delete-artifacts-action@v1
        with:
          log_level: "debug"
          min_bytes: "0"
          run_id: "${{ github.run_id }}"
